#! configuration/base.yaml
application:
  port: 8000
database:
  host: "localhost"
  port: 5433
  username: "postgres"
  password: "password"
  database_name: "newsletter"
emailclient:
  base_url: "http://127.0.0.1"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
  token: "POSTMARK_API_TEST"