#! configuration/base.yaml
application:
  port: 8000
database:
  username: "postgres"
  password: "password"
  database_name: "newsletter"
emailclient:
  sender_email: "noreply@ilkablumentritt.de"
  timeout_milliseconds: 10000