#! configuration/base.yaml
application:
  port: 8000
database:
  host: "192.168.178.3"
  username: "postgres"
  password: "password"
  database_name: "newsletter"
emailclient:
  sender_email: "noreply@ilkablumentritt.de"
  timeout_milliseconds: 10000
redis_uri: "redis://192.168.178.3:6379"