#! configuration/base.yaml
application:
  port: 8000
database:
  host: "localhost"
  port: 5433
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: 1d419ed1-109d-4665-9c32-6307e5f73b9a
  timeout_milliseconds: 10000