#! #! configuration/local.yaml
application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1:8000"
database:
  require_ssl: false
emailclient:
  # set this on digital via APP_EMAILCLIENT__TOKEN
  token: "POSTMARK_API_TEST"