#! #! configuration/production.yaml
application:
  host: 0.0.0.0
  base_url: "https://zero2prod.drflowerkick.duckdns.org:443"
database:
  host: "192.168.178.3"
  port: 5435
  require_ssl: false
emailclient:
  base_url: "https://api.postmarkapp.com"
redis_uri: "redis://192.168.178.3:6379"